services:
  ui:
    build: .
    profiles: ["homolog", "main"]
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    networks:
      - shared-network

networks:
  shared-network:
    external: true
