services:
  ui:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    profiles: ["homolog", "main"]
    ports:
      - "127.0.0.1:5173:80"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
